### ISSUE TITLE
Windows 7 Support

### ISSUE THREAD

**Issue by Beardanidas** [kprinssu/anne-keyboard-windows#10]
I know its probably a long shot, but about 1/3 of steam is still on Windows 7. Any chance for support?

**Comment by kprinssu** [comment]
Unfortunately, the Universal Windows Platform (UWP) apps are not officially supported by Microsoft. This projects depends on key APIs that are only supported by UWP, and hence the requirement for Win8/10.

I (or someone) else may be able to create something for Win7, but it seems like there isn't an easy of way doing it in C# (or any other language for that matter). Support for any high-level Bluetooth Low Energy APIs in Window 7 is very lacking.
