### ISSUE TITLE
Media controls

### ISSUE THREAD

**Issue by szensk** [kprinssu/anne-keyboard-windows#11]
When assigned to the fn layer the media controls (volume up/down, mute) do nothing. I'm on Windows 10, with the latest firmware (1.2.0). Any ideas?

**Comment by kprinssu** [comment]
I believe that I got the keys mapped incorrectly. Looks like I will have to take a look at how the keys are set in the official app.

**Comment by kprinssu** [comment]
From a quick check, it seems that it only works on Macs. Can you also check using the phone app and your own keyboard?

**Comment by szensk** [comment]
Ah you're right. Set with the phone and it only works on my Mac. I have to ask Obins about that.

**Comment by kprinssu** [comment]
Hopefully the Obins dev fix this in this next update.
