### ISSUE TITLE
Not saving profiles

### ISSUE THREAD

**Issue by mttx** [kprinssu/anne-keyboard-windows#12]
Not sure if this is the right place, but the App doesnt save profiles I created. 

Am I doing something wrong or is this a bug?

**Comment by kprinssu** [comment]
You got the right place. It should be saving profiles correctly with the latest version (1.0.2).
 Can you tell me when you downloaded the app? Do you see the layout changing option?

**Comment by mttx** [comment]
I got the app this week, I think wednesday or so. Ill try the new version, Im on 1.01

**Comment by kprinssu** [comment]
You should have the latest version... I'm unsure of what could cause this. Can you let me know if the re-downloaded version of 1.0.2 still does not save profiles.

**Comment by mttx** [comment]
Got the new version and it works! Thanks 👍 

However my layout changed and I cant fix it. Im using the standard layout and if I press Fn+ /? which is supposed to be "delete" doesnt do anything anymore. Instead Fn+.> is now delete. 

The standard fn-layer:
http://i.imgur.com/TtyDQoB.png

**Comment by kprinssu** [comment]
Looks a small bug in the default layout. You can change it back using the app, but I'll add in a fix soon.

**Comment by mttx** [comment]
Yeah I changed it via the app. Do you think its possible to add other keys from other countries layouts?  Specifically this one http://i.imgur.com/Hz1qjCS.png since im typing on the German layout and this key is missing :(

**Comment by kprinssu** [comment]
Sorry, the keyboard only supports US ANSI layout.

**Comment by mttx** [comment]
Ah alright no big deal
