### ISSUE TITLE
Issues installing on Win8

### ISSUE THREAD

**Issue by ghost** [kprinssu/anne-keyboard-windows#13]
Hi, I tried to install this on Windows 8 and ran into problems.

```
Add-AppxPackage : Deployment failed with HRESULT: 0x80080204, The Appx package's manifest is invalid.

error 0x80080204: App manifest validation error: The document root element m:Package must be defined in the
http://schemas.microsoft.com/appx/2010/manifest namespace.

NOTE: For additional information, look for [ActivityId] 0efaadb6-2758-0001-dcdd-fa0e5827d201 in the Event Log or use
the command line Get-AppxLog -ActivityID 0efaadb6-2758-0001-dcdd-fa0e5827d201

At Add-AppDevPackage.ps1:388 char:13
+             Add-AppxPackage -Path $DeveloperPackagePath.FullName -DependencyPath ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\..._arm.appxbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

Error: Could not install the app.  To ensure security, please consider uninstalling the signing certificate until you ca
n install the app.  Instructions for doing so can be found here:
http://go.microsoft.com/fwlink/?LinkId=243053
```

Would you also mind telling me what certificate it installed so I can remove it if I can't get it to work?

**Comment by kprinssu** [comment]
Looks like you don't have developer mode enabled. Run this command in an escalated Powershell terminal (run Powershell with administrator privileges):
`Show-WindowsDeveloperLicenseRegistration`

Then try installing it again.

**Comment by ghost** [comment]
I already went through that process and got a license that is good for a year. I used the command you suggested and it installed a license again, but I still get the same error.

**Comment by kprinssu** [comment]
Sorry, but there is not much else I can suggest. From that specific error message, it looks a sideloading issue (certificate is not signed/verified, see https://msdn.microsoft.com/en-us/library/windows/apps/hh975356(v=vs.110).aspx). The easiest way for me to trouble shoot is to install it locally on a Win8 machine, but I currently do not have the time to do so. Also, please ensure that you are using Win8.1, and not the original Win8.

If you are okay with building and installing it locally, you can checkout the repository and install via VS2015 Community Edition.

**Comment by kprinssu** [comment]
I am closing this issue for now. Feel free to re-open this again if you are still having troubles installing it on Windows 8
