### ISSUE TITLE
[Question/Enhancement] - USB Config

### ISSUE THREAD

**Issue by ghost** [kprinssu/anne-keyboard-windows#14]
I understand this app uses the same protocol (so to speak) to configure the anne keyboard as the mobile apps use? Is the anne keyboard set up in such a way that it can be configured by a USB host?

**Comment by ghost** [comment]
Apologies. I have researched [the reddit page](https://www.reddit.com/r/MechanicalKeyboards/comments/4us0uk/anne_pro_windows_10_app/) and seen that they keyboard supports bluetooth configuration only.

**Comment by kprinssu** [comment]
The keyboard only supports backlight control via Bluetooth.
