### ISSUE TITLE
Windows 8 Installation failure

### ISSUE THREAD

**Issue by timm0e** [kprinssu/anne-keyboard-windows#15]
```
Fehler 0x80080204: Überprüfungsfehler bei App-Manifest: Das Dokumentstammelement "m:Package" muss im Namespace
"http://schemas.microsoft.com/appx/2010/manifest" definiert sein.

HINWEIS: Wenn Sie weitere Informationen wünschen, suchen Sie im Ereignisprotokoll nach "[ActivityId]
0dd10402-717e-0000-9f1f-d10d7e71d201", oder verwenden Sie die Befehlszeile "Get-AppxLog -ActivityID
0dd10402-717e-0000-9f1f-d10d7e71d201".

In C:\Users\Tim\Downloads\AnneProKeyboard_1.0.2.0\AnneProKeyboard_1.0.2.0\Add-AppDevPackage.ps1:388 Zeichen:13
+             Add-AppxPackage -Path $DeveloperPackagePath.FullName -DependencyPath ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\Tim\Do..._arm.appxbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

I hope you can get some info out of this :)

If you need further information/testing, feel free to contact me

**Comment by kprinssu** [comment]
Do you mind if you can post a rough translation of what that error?

**Comment by timm0e** [comment]
Error 0x80080204: Validation error in App-Manifest: The documentrootelement "m:Package" needs to be defined in the namespace "http://schemas.microsoft.com/appx/2010/manifest"

**Comment by kprinssu** [comment]
Looks like a language mismatch (see http://wasker.github.io/articles/2016-01-12-universal-windows-apps-uwp-package-manifest-not-valid/). I'll have a fix made asap.

Edit: I do not have access to a Windows machine right now and it may take a while to get a proper build pushed out.

**Comment by kprinssu** [comment]
After spending few more minutes looking at the error im detail. I have found that is linked to how to sideload apps in Windows 8. Can you confirm that you have "developer" mode enabled?

**Comment by timm0e** [comment]
Yep, I aquired a developers license (as specified here: www.makeuseof.com/tag/sideload-apps-windows-8-10/)

**Comment by kprinssu** [comment]
I'll need more information on why that error is occurring. Can you please try running this command in this powershell: `Get-AppxLog`

**Comment by anonymous83** [comment]
same issue here. using windows 8.1. Developer mode enabled but get the same erro when installing the application

**Comment by anonymous83** [comment]
Message
 -------
 The calling process is C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
 Started deployment Add operation on a package with main parameter:
 file:///C:/AnneProKeyboard/AnneProKeyboard_1.0.1.0_x86_x64_arm.appxbundle,
 dependency parameters: file:///C:/AnneProKeyboard/Dependencies/x86/Microsoft.NET
 .Native.Framework.1.3.appx, file:///C:/AnneProKeyboard/Dependencies/x86/Microsof
 t.NET.Native.Runtime.1.4.appx,
 file:///C:/AnneProKeyboard/Dependencies/x86/Microsoft.VCLibs.x86.14.00.appx, fil
 e:///C:/AnneProKeyboard/Dependencies/x64/Microsoft.NET.Native.Framework.1.3.appx
 , file:///C:/AnneProKeyboard/Dependencies/x64/Microsoft.NET.Native.Runtime.1.4.a
 ppx,
 file:///C:/AnneProKeyboard/Dependencies/x64/Microsoft.VCLibs.x64.14.00.appx and
 Options: ForceApplicationShutdownOption. See
 http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app
 deployment issues.
 The app bundle signature was validated for core content of the app bundle
 published by CN=Kishor. App packages won't be validated until they are read.
 The bundle streaming reader was created successfully for bundle
 2f23bec5-1506-4ef7-9768-7a82dce46a09_1.0.1.0_neutral_~_w7amz0rwn319p.
 error 0x80080204: Opening the package from location file:///C:/AnneProKeyboard/D
 ependencies/x86/Microsoft.NET.Native.Framework.1.3.appx failed.
 error 0x80080204: Failure to get staging session for: file:///C:/AnneProKeyboard
 /Dependencies/x86/Microsoft.NET.Native.Framework.1.3.appx.
 error 0x80080204: AppX Deployment operation failed. The specific error text for
 this failure is: error 0x80080204: App manifest validation error: The document
 root element m:Package must be defined in the
 http://schemas.microsoft.com/appx/2010/manifest namespace.
 The app package signature was validated for core content of the app package
 published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond,
 S=Washington, C=US. Payload won't be validated until the files are read.
 error 0x80080204: App manifest validation error: The document root element
 m:Package must be defined in the
 http://schemas.microsoft.com/appx/2010/manifest namespace.

**Comment by timm0e** [comment]
Hey there,

When I was bored in class, so i went through the App Manifest with a Text Editor

`<Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10" xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest" xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" IgnorableNamespaces="uap mp">`

The required namespace http://schemas.microsoft.com/appx/2010/manifest is not even included

` <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.0.0" MaxVersionTested="10.0.0.0" />`

Windows 8.1 uses Version Number 6.1 internally

When Opening the Project in Visual Studio on 8.1 with all SDKs it is not possible to lower the MinVersion to something compatible with Windows 8.1.

When creating a Project for 8.1, a whole different Project Template has to be selected. Maybe porting it over to the 8.1 one would work, but I've never developed something for UWP.

I guess the whole BLE stuff is available for non-UWP apps, so maybe I'll try building something with WPF, but no promises here.

May I ask how you reversed the App? You decompiled it, or did you Wireshark all the BT Traffic between the keyboard and an emulator?

**Comment by kprinssu** [comment]
I did a combination of the two to reverse-engineer the protocol. I did a quick write up on Reddit and I currently do not have the time to do a formal write up of the process. 

It looks like I am targeting Win10 and only Win10. I will do a re-build ASAP.

**Comment by kprinssu** [comment]
@timm0e I may have not realised that I am building against the Win10 SDK. The UWP platform should be easy to port over to other platforms since the APIs should not change. If you want help on how I reversed the Bluetooth protocol, please e-mail at kprinssu@uwaterloo.ca

I can create a formal write-up if you so need it.

**Comment by kprinssu** [comment]
It seems that I was mistaken and UWP only supports Windows 10. Adding support for Win8 will result in a total re-write of the app and I do not have the time to do so. I will close this ticket for the time being.
