### ISSUE TITLE
Windows 10 LTSB install issue

### ISSUE THREAD

**Issue by Nielwulf** [kprinssu/anne-keyboard-windows#16]
I am having issues installing the Annepro desktop app on my Windows 10 Enterprise LTSB computer.

Below you will find the install errors AND the Get-AppxLog

http://pastebin.com/jP6Px35n

It looks like it is failing on installing the dependencies but I cant find which one it is having trouble with or if there is a separate one that needs to be installed for my version of Win10.

**Comment by kprinssu** [comment]
I believe that your Windows 10 version is too old. Can you grab the latest version of the app and try installing it? It should support older versions, if not please let me know and I will try to get a proper build out.

**Comment by Nielwulf** [comment]
I was following the link from the /r/annepro and didn't notice a new version of the app was out there. I was able to install the app without issue, however it won't start with UAC disabled. So two steps forward and one step back?

**Comment by kprinssu** [comment]
It should work with UAC disabled. Can you provide information on why/how it won't start?

The app requires Bluetooth permissions, so I would check there. If UAC is also disabled, then the app should work.

**Comment by Nielwulf** [comment]
When I attempt to start the app, i get a Windows 10 styled prompt saying the app can't open with UAC disabled. I have included a screenshot of the message that I receive.
![app](https://cloud.githubusercontent.com/assets/6455774/23170865/5eacab66-f816-11e6-94fc-7790b14bb155.png)

**Comment by kprinssu** [comment]
Contradictory what I said before, you need to enable User Account Control (UAC). Looking at Microsoft's Developer docs, you'll need UAC enabled for any UWP app to work.

**Comment by Nielwulf** [comment]
Ahhh, it all makes sense now. Thanks for the app, i'll enable UAC if i need to make any changes. Until then I'll just use the phone app.
