### ISSUE TITLE
Colors not assigned to correct buttons

### ISSUE THREAD

**Issue by jacobbjo** [kprinssu/anne-keyboard-windows#19]
It works correctly on the android app so I assume my keyboard is not the problem. 

When I use the windows app the colors does not get assigned to the correct buttons, see picture. 

![bug anne pro](https://cloud.githubusercontent.com/assets/1240025/24744989/3d2fe96a-1ab4-11e7-95f5-36bb87cbaf5b.png)

**Comment by kprinssu** [comment]
Which version of the app are you using?

Have you tried getting the latest version from Github?

The latest version of the app should work properly. That screenshot you provided looks from a very old build.

**Comment by jacobbjo** [comment]
Yeah, old version i found on the subreddit wiki. now its working!
