### ISSUE TITLE
Proper RGB colour selection

### ISSUE THREAD

**Issue by kprinssu** [kprinssu/anne-keyboard-windows#2]
Currently, the app is using 3 sliders for selecting colours. There exist better alternatives to selecting a colour (i.e. a colour wheel). However, such an alternative will be need to be custom made to support XAML.

A potential third party library was mentioned here, https://github.com/kprinssu/anne-keyboard-windows/pull/1 and https://github.com/kprinssu/Color_Picker

**Comment by Kitinni** [comment]
Good find on the updated RadialColorPickerCV, I love the design of this and wanted to use it but hadn't quite figured out how to update it for use with UWP.
I'll have a go at adding this later

**Comment by kprinssu** [comment]
The original library doesn't seem to be working on Windows 10, but the fork above should work on Windows 10. There seems to be dependency errors, but that should be easy to fix.

**Comment by kprinssu** [comment]
I created a Nuget package with the above project tohttps://www.nuget.org/packages/Color_Picker/1.0.2
Let me know if there are any issues.

**Comment by kprinssu** [comment]
I have added a colour picker in https://github.com/kprinssu/anne-keyboard-windows/commit/283c3cca3ffbe539725ff3fde15fe589d94a4084, UI tweaks will be needed, but it now looks a lot cleaner.

**Comment by Kitinni** [comment]
That looks clean indeed, thanks for this component @shivamcv and @rolandsmeenk for updating it !
