### ISSUE TITLE
Where are the profiles saved?

### ISSUE THREAD

**Issue by thomasf** [kprinssu/anne-keyboard-windows#20]
I'd like to edit them with a text editor, if possible.. 
The GUI is too clunky when managing many profiles.

**Comment by thomasf** [comment]
btw.. 

I have kind of started coding a linux only (for now) command line programmer.. I haven't started implementing the BT stuff yet but I have divided the configurations into four/five data types:

1. A palettes/color scheme 
2. A color mapping layout which uses a palette
3. A key mapping layout (maybe considering having the fn-layer config separated)
4. A Preset (a combination of any of 1-3)

I'll probably go for a text only config format, at least to start with..

**Comment by kprinssu** [comment]
The config files are stored in temporary folder and the path changes for each system. Take a look at https://github.com/kprinssu/anne-keyboard-windows/blob/master/AnneProKeyboard/MainPage.xaml.cs#L101 for more information.

Feel free to make a Linux port! 

If you got an idea for an improved UI, then submit a PR. I'll review and merge it.

Most of the byte array logic is in the app, if you run into issues just ping me and I'll help out.

**Comment by thomasf** [comment]
Thanks for the info and the ground work for the BT communication stuff.

I did search for a `KeyboardProfilesData` file in my users local app data folder.. I probably did some mistake, I haven't developed for windows API's for at least 15 years so I have no idea how all those things works now.. I'll probably figure it out.

**Comment by thomasf** [comment]
found it by mounting the partition and searching form my linux os... I'm the worst at windows, it seems like I can't even find files correctly :)
