### ISSUE TITLE
Crash when deleting profile

### ISSUE THREAD

**Issue by SuperCuber** [kprinssu/anne-keyboard-windows#26]
Steps to reproduce:

1) Create a new profile
2) Move to "lights" screen
3) Try to delete said profile
4) App should crash after a couple seconds of freezing, any changes to profiles not saved

**Comment by ethanmsmith** [comment]
Alright, so think I know why this is happening, could you tell me what profile is being deleted in order in the dropdown? e.g. are you deleting the first or last profile in the list, or something in between?

**Comment by SuperCuber** [comment]
I tested it when I had 2 profiles and tried deleting the 2nd one

**Comment by kprinssu** [comment]
Which version of the app are you using?

**Comment by SuperCuber** [comment]
Using version 1.0.4

**Comment by ethanmsmith** [comment]
I think I found the problem. I've taken profile logic out of individual pages. (Really should have done that when I refactored the pages, but I didn't want to.) @kprinssu What is the build process? Ill build my fork and have @SuperCuber and possibly others confirm its fixed.

**Comment by SuperCuber** [comment]
@ethanmsmith sure thing, make sure to ping me on that fork though

**Comment by ethanmsmith** [comment]
Perfect. Once it's ready, will do

**Comment by kprinssu** [comment]
@ethanmsmith can you please create a PR? I will run a new build on my Windows VM after some testing.

**Comment by ethanmsmith** [comment]
So, I did fix the profile crashing, but since I can never do one thing at a time, I changed a decent chunk of the current code to native XAML controls. I need to fix a few minor bugs I introduced...

**Comment by kprinssu** [comment]
Okay. Tag me in the new PR and I’ll do the rest.

**Comment by ethanmsmith** [comment]
Newest build should fix this issue @SuperCuber

**Comment by SuperCuber** [comment]
@ethanmsmith Tested, looks like the issue is fixed. Closing.
