### ISSUE TITLE
Does not recognize keyboard when wired

### ISSUE THREAD

**Issue by SuperCuber** [kprinssu/anne-keyboard-windows#27]
From what I see, app only recognizes keyboard via bluetooth and doesn't work when connected with wire

**Comment by ethanmsmith** [comment]
It doesn't not work over wire, only bluetooth

**Comment by kprinssu** [comment]
@ethanmsmith is correct. This will only work over Bluetooth Low Energy (Blutetooth 4.0).

**Comment by SuperCuber** [comment]
@kprinssu so that's intended behavior? Probably should leave it open with enhancement tag

**Comment by ethanmsmith** [comment]
It's a keyboard limitation, not our choice

**Comment by kprinssu** [comment]
I would pass the blame on this over to the manufacturer, Obins. It was probably an easy to choice to make, it is considerably cheaper to not create a USB driver.
