### ISSUE TITLE
Leaving unused keys as blank rather than "None"

### ISSUE THREAD

**Issue by will-hedges** [kprinssu/anne-keyboard-windows#29]
Thanks for this awesome project. Editing the AP board on the phone app is pretty slow. Your app is a real lifesaver. 

One thing I noticed from the app version is that programming the function layer is easier when you leave unused keys blank, rather than using "None." Is there a way to utilize this in the Win10 app?

Again, thanks for taking the time to port this!

**Comment by kprinssu** [comment]
This is will be considered for a future release. As of this moment, I do not have time to add features to the app.

**Comment by will-hedges** [comment]
Thanks for the response. I certainly understand considering this is a side project. I appreciate you developing it in the first place.

**Comment by kprinssu** [comment]
Fixed in the latest build. Thanks @ethansmith.
