### ISSUE TITLE
Anne Pro connected to windows but app doesn't recognize it

### ISSUE THREAD

**Issue by nraiha** [kprinssu/anne-keyboard-windows#30]
I have connected Anne Pro to windows with the Bluetooth dongle.  (connected with CSR Bluetooth-radio)
The app just keeps waiting for the sync and status stays "not connected".

Any workarounds?

**Comment by kprinssu** [comment]
Does the keyboard work over Bluetooth (as in can you type using it)?

**Comment by nraiha** [comment]
Yes it works perfectly.

I've also tried to restart the Anne Pro Keyboard program few times.

**Comment by kprinssu** [comment]
Can you check if the device is communicating on Bluetooth aloe Energy (BY 4.0)? There is a guide on the obins website that explains how to do this.

**Comment by rmcmilli** [comment]
I'm having the same problem. I'm using the dongle.  I can type using Bluetooth and it is using LE

**Comment by rmcmilli** [comment]
Quick update: I uninstalled, unplugged, and reinstalled and now it's connected.

**Comment by kprinssu** [comment]
Next time please create your own Github issue. I am closing this issue for now.
@nraiha please feel free to reopen if you are still facing issues.
