### ISSUE TITLE
Add-AppDevPackage.ps1 missing from repo

### ISSUE THREAD

**Issue by balintd** [kprinssu/anne-keyboard-windows#31]
The README says for installing the application one should right click on `Add-AppDevPackage.ps1`, but there is no file named like that in the repository.

**Comment by kprinssu** [comment]
This is built automatically by Visual Studio for binary releases. The Git repository does not contain the binary version and only the source code.

The file can be found within the zip archives  on the “Releases”.

**Comment by balintd** [comment]
Thanks!
