### ISSUE TITLE
Remapping non-standard keys

### ISSUE THREAD

**Issue by claychinasky** [kprinssu/anne-keyboard-windows#33]
Hi,

Is it possible to add support for remapping keys to F13-F24 ?
I use them as modifier keys for custom  action in autohotkey etc. For example I like to remap Anne key for F15 so no other standard key combination will brake because no application uses F12+ keys.

**Comment by kprinssu** [comment]
I do not this is possible. The official application does not support it and I have no way of replicating that behaviour on here.

Please let me know if I am incorrect, I will reopen this issue and will look into it.
