### ISSUE TITLE
 cert expired

### ISSUE THREAD

**Issue by rossmilkq** [kprinssu/anne-keyboard-windows#34]
The cert expired for the install on the Dec 11, 2018. Can someone update the cert for the appxbundle.

**Comment by kprinssu** [comment]
Do you mean December 11, 2017? It is currently May 8, 2018 and the certificate *should* not have expired by now (as of this response).

Which version of the app are you using?

**Comment by rossmilkq** [comment]
I am sorry, your right I posted the wrong date and was trying to install an earlier version. It worked with 1.0.4.
