### ISSUE TITLE
Fail to save profiles when app exiting

### ISSUE THREAD

**Issue by ethanmsmith** [kprinssu/anne-keyboard-windows#37]
The app occasionally fails to save profiles when exiting. Yet to reproduce on a consistent basis, but looking into it.  
If this happens to you, please tell me the last actions you performed before exiting the app.

**Comment by kprinssu** [comment]
My guess is there is an exception being raised (which exception will be hard to debug without logs).  The app will silently fail in order to not cause the app to crash.

**Comment by ddejohn** [comment]
Happening to me, too, on every app exit

**Comment by kprinssu** [comment]
The latest commit, https://github.com/kprinssu/anne-keyboard-windows/commit/0c8c8e4235cf642811b557a3364dc7ea0a5d60ea, should fix the issue. I am pushing out a new build.

Profiles *will not* be saved on app exit. It will automatically save when you sync the profile.
