### ISSUE TITLE
1.0.6 can't connect to keyboard

### ISSUE THREAD

**Issue by ddejohn** [kprinssu/anne-keyboard-windows#39]
Bluetooth connection status at bottom left is "Not Connected" despite the keyboard being connected to the computer and functioning properly. Unable to make any changes. I've tried wired and wireless, and I've also tried repairing the keyboard to the computer to no avail. I may have gotten a faulty KB, because I've been having issues with the BT, but FWIW, 1.0.5 was able to connect and make changes to the KB.

**Comment by kprinssu** [comment]
Can you try connecting the keyboard to your phone? Download the official obins app and check if you can control the keyboard from there.

**Comment by ddejohn** [comment]
I am able to connect and control the keyboard from my Android phone.

**Comment by kprinssu** [comment]
I would suggest you try to connect to Windows and check if you can type with it  wirelessly (as in,  connect over Bluetooth, ensure that the USB cable is not connected).

Then try using the app.

**Comment by ddejohn** [comment]
Check the OP. I've already confirmed the keyboard works properly under bluetooth connection.

**Comment by ddejohn** [comment]
The "sync profile" option is not grayed-out, though. But when I try to sync, a message flashes briefly saying that it failed to sync and that the exception was handled.

**Comment by kprinssu** [comment]
Can you open up Bluetooth settings and take a screenshot?

The settings should like so http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/uploads/2016/08/bluetooth-in-windows-10.png

**Comment by ddejohn** [comment]
https://i.imgur.com/3kaWCHr.png

**Comment by ddejohn** [comment]
So I figured out the problem. Somehow, my computer had assigned vscode as the default application to .ps1 files, which was preventing the app from working. Changed it back to notepad, and "run in powershell" reappeared in the .ps1's context menu. App works fine now. I'm not sure what caused this to happen, but glad to know it wasn't an issue with the app.
