### ISSUE TITLE
[request] If possible, allow for changing layouts via wired connection instead of bothering with connecting the app using bluetooth

### ISSUE THREAD

**Issue by ddejohn** [kprinssu/anne-keyboard-windows#40]
Changing keyboard layouts and lighting schemes is kind of a set-and-forget type of process. I think it'd be a lot easier and more reliable to just use a wired connection in order to make changes to the KB.

**Comment by kprinssu** [comment]
Wired connection will not be supported due to the limitations of the keyboard firmware.

**Comment by ethanmsmith** [comment]
Your best bet is the anne-key firmware. I opened an issue for wired on their github [here](https://github.com/ah-/anne-key/issues/64). There is also someone working on a qmk port for the Anne [here](https://github.com/josecostamartins/qmk_firmware)
