### ISSUE TITLE
Dynamic lighting implementation

### ISSUE THREAD

**Issue by baalimago** [kprinssu/anne-keyboard-windows#41]
Hello! 

I want to implement configurable dynamic lighting (which will be similar to the preset on the keyboard, but configurable by anyone using the windows app) so, as you might have noticed, I forked and plan to use your underlying work as a basis for this.

I saw that you've borrowed some code from their app to implement the button color swap into the keyboard, how did you get access to their app code? Could you help me get access (the APK doesn't exist on the reddit wiki anymore, can't find it anywhere else)? I wish to see how Obins implemented the different presets and use that as a template for implementing similar functionality myself. 

I'm not that often on github, so could you please email me at [removed], if you decide to help?

Much appreciated, thanks!

**Comment by kprinssu** [comment]
I would suggest you remove your email off Github (prevent it from being scraped and spammed). I decompiled the app and reverse engineered what was going on. 

Here is the app decompiled: https://github.com/metr1xx/anne-pro-community-app

I am closing this issue since it’s not an bug associated with the windows app.

**Comment by MvEerd** [comment]
The APK is available on the obins website: http://www.obins.net/app_dl.php

You can find more info on the disassembled APP here;
https://hi-a.github.io/annepro-key/
https://github.com/hi-a/annepro-key


The (dynamic) presets are not actually sent by the app, instead they are a part of the firmware on the STM32 chip which is dedicated to control the LEDs
The LED chip and firmware receive messages from the main STM32 chip / firmware which in turn come through the app over bluetooth

There has also been some talk about dynamic lighting in the Discord for the alternative Rust firmware;
https://github.com/ah-/anne-key
 
And some work has been started to create open source firmware for the chip that handles the LED; https://github.com/ah-/anne-led
