### ISSUE TITLE
Can't get dropdown UI to allow remapping of keys selection

### ISSUE THREAD

**Issue by chai** [kprinssu/anne-keyboard-windows#42]
Running Windows 10 1803 (Build 17134.81), noticed that the app is not letting me select a different key to remap. Its seem to be a display/layer issue as sometime you can see the dropdown for selecting a different key appear briefly. Please see the attached video for details.

Thanks for creating this tool.
[Anne Pro Keyboard 4_06_2018 09_45_30.zip](https://github.com/kprinssu/anne-keyboard-windows/files/2068757/Anne.Pro.Keyboard.4_06_2018.09_45_30.zip)

**Comment by ethanmsmith** [comment]
Can you tell us anything you did before this happened? Were you ever able to get the dropdown to show correctly? Can you try updating to the latest version and see if the bug persists?

**Comment by kprinssu** [comment]
I fixed the issue in 1.0.6. I suggest you update and grab the latest version of the app.
