### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by rkg0612** [kprinssu/anne-keyboard-windows#43]
I get a certificate error whenever I try to install the app. Any way to fix this?

"The developer certificate has expired. One possible cause is the system clock isn't set to correct date and time. If the system settings are correct, contact the app owner to recreate a package or bundle with a valid certificate"

My system date and time are both correct. I think the app certificate is the real problem. Please fix. Thanks!

**Comment by ethanmsmith** [comment]
Related to #34?

**Comment by kprinssu** [comment]
I suggest you update your app.
