### ISSUE TITLE
Why does the app want to install a trusted root certificate?

### ISSUE THREAD

**Issue by filmerjarred** [kprinssu/anne-keyboard-windows#46]
Installing a trusted root ca cert for am app that doesn't seem like it needs it makes me nervous :S. Why would this be required?

**Comment by ethanmsmith** [comment]
Here's documentation on why it's needed https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps#sideload-your-app-package

Basically, you are sideloading instead of installing from the trusted windows store. So you need to tell windows that the developer is trusted

**Comment by kprinssu** [comment]
The release builds are signed by an untrusted test certificate. I do not want to pay the fee to get a Windows code-signing certificate. You can always grab a clone of this Git repository, build, and deploy the app locally.
