### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by gnogas** [kprinssu/anne-keyboard-windows#47]
![image](https://user-images.githubusercontent.com/23090984/54213734-304c0a00-44e5-11e9-8060-d5923291919b.png)
When i install i get this error, my windows 10 is updated.

**Comment by ethanmsmith** [comment]
Use obins' official app. This app hasn't been updated in a bit and could be broken, who knows.

**Comment by gnogas** [comment]
> Use obins' official app. This app hasn't been updated in a bit and could be broken, who knows.

Maybe im dumb but i can't find it for windows, does it not exist or am i just bad at searching?

Edit: nevermind i found it! http://en.obins.net/obinslab-starter

**Comment by robinlarondelle** [comment]
@ethanmsmith if this repo isn't updated, shouldn't it be marked archived? There is no way of working around the expired certificate, and if you are not willing to update it or create a new one, you should probably archive the repo

**Comment by ethanmsmith** [comment]
Perhaps, but it is not my repo to archive
