### ISSUE TITLE
Certificate has expired.

### ISSUE THREAD

**Issue by iGnotusCs** [kprinssu/anne-keyboard-windows#48]
Certificate has expired (valid from 5/18/2018 to 5/18/2019). Can anyone renew this please? :) 
![Screenshot_3](https://user-images.githubusercontent.com/9625522/59205091-c22de680-8baa-11e9-980a-c65511f1d7b8.png)

**Comment by ethanmsmith** [comment]
#43 also https://github.com/kprinssu/anne-keyboard-windows/issues/47#issuecomment-472069240

**Comment by Sov3rain** [comment]
Can someone repackage the tool? Right now we can't install it.

**Comment by kprinssu** [comment]
I will be doing a new build later this weekend. Please wait until then.

**Comment by Alexandros-Demirtzoglou** [comment]
> 
> 
> I will be doing a new build later this weekend. Please wait until then.

My birthday is on June 12th! Do you think you could renew the certificate so I can use your great app please? 😄

**Comment by NaanMan** [comment]
Well then

**Comment by iluretar** [comment]
Any news on the new build?

**Comment by ethanmsmith** [comment]
This is no longer actively maintained. Check out https://github.com/IOIIIO/anne-keyboard-windows for the latest fork

**Comment by NaanMan** [comment]
That one also says the certificate has expired >_>

**Comment by daewon** [comment]
@ethanmsmith I downloaded the file to the linked repository and ran it, but it still says that the certificate has expired.

Is there any way I can use it?

**Comment by kprinssu** [comment]
Due to me working full-time and switching over to Linux/macOS, I do not think I will be providing support for this project.

Please consider using the official Obins app or building this app from scratch.
