### ISSUE TITLE
Macro Support

### ISSUE THREAD

**Issue by kprinssu** [kprinssu/anne-keyboard-windows#5]
The official app has macro support by recording key presses. The Windows app will also need to support this feature. However, this feature is complex and will require some time to implement.

**Comment by kprinssu** [comment]
I do not have the time to add new features to the app.

**Comment by mainrs** [comment]
Do you mean the official windows/Mac app or the phone app?

**Comment by ethanmsmith** [comment]
Phone app. This project was made before obins had their official desktop app
