### ISSUE TITLE
Profile selection / renaming

### ISSUE THREAD

**Issue by Kitinni** [kprinssu/anne-keyboard-windows#6]
Currently it's not very clear how to select a Profile, clicking the name on the left will focus on a textbox to edit so only the area around the textbox can be clicked to select the profile.

![anneprofile](https://cloud.githubusercontent.com/assets/13258131/17258641/2931e2f8-55c8-11e6-971e-77d9dac5f27a.png)

I thought of 2 possible improvements here, the easiest would be to have the Profile list on the left be labels and change the 'Selected Profile Label' to be a textbox for editing instead (Either click to edit, or add an edit icon so it's clear http://fontawesome.io/icon/pencil/ )

Another way of handling it would be to have clicking in the list once select the profile and double-click to edit the name, but this would involve hiding the textbox to replace it with a label and showing it when the text is double-clicked. It might also be less self-explanatory that way

Do you have any thoughts on this before I work on a PR?

**Comment by kprinssu** [comment]
Sounds a like good idea. XAML has a SymbolIcon element, and all of the icons in the app are using it. The UWP framework has default icons you can use, here's a good list that you can take a look at: https://msdn.microsoft.com/library/windows/apps/dn252842

**Comment by kprinssu** [comment]
Added this feature in https://github.com/kprinssu/anne-keyboard-windows/commit/838de9141a0d6799ecc37d06cfda88b9ac748425

Let me know if you spot any bugs.

**Comment by Kitinni** [comment]
Awesome, that's what I was going for but I had issues with the IDs being the same when relying solely on the count. Good solution with the `KeyboardProfiles_CollectionChanged` function. 

I had a play around creating and deleting some profiles and it no longer deletes the wrong profiles when creating and deleting multiple with the same label :+1:
